- name: install backup program
  package:
    state: present
    name: borg

- file:
    state: directory
    path: /backup

- mount:
    fstype: auto
    path: /backup
    src: /dev/disk/by-label/BACKUP
    state: mounted

- command: borg init -e keyfile /backup/backups/ creates=/backup/backups/

- command: gpg --recv-key 0x7468564DA7B003F8

- shell: borg key export /backup/backups/ /dev/stdout | gpg -e -r 0x7468564DA7B003F8
