---
- name: setup laptops
  hosts: laptops
  roles:
    - workstation
    - battery-saver

- name: run tests on test servers/vagrant boxes
  hosts: test
  roles:
    - workstation

- name: install dotfiles while run on our own
  hosts: localhost
  connection: local
  roles:
    - dotfiles
