---
- hosts: all
  roles:
    - common

- hosts: all:!archlinux
  roles:
    - update

- hosts: laptops
  roles:
    - user
    - graphical
    - battery-saver
    - wifi-basic
    - office
    - printer-scanner
    - xyne-repo
    - pacserve
