---
- hosts: all
  roles:
    - common

- hosts: laptops
  roles:
    - workstation
    - battery-saver

- hosts: test
  roles:
    - workstation

- hosts: localhost
  connection: local
  roles:
    - dotfiles
