---
- hosts: desktops:laptops
  vars_prompt:
    - name: user_password
      prompt: What is the user's password?
      default: password
      private: yes
      
  roles:
    - workstation

- hosts: laptops
  roles:
    - battery-saver

- hosts: test
  roles:
    - workstation
