---
- hosts: localhost
  connection: local
  roles:
    - dotfiles
  tasks:
    - meta: end_play

- hosts: all
  roles:
    - common

- hosts: laptops
  roles:
    - workstation
    - battery-saver

- hosts: test
  roles:
    - workstation

