---
- name: install user programs
  package:
    state: present
    name:
      - sudo
      - linux-zen
      - linux-zen-headers
      - bash-completion
      - ccid
      - opensc
      - libusb-compat
      - pkgfile

- name: configure smartcard
  block:
    - name: enable smartcard service
      service:
        name: pcscd
        enabled: yes

    - name: start smartcard service
      service:
        name: pcscd
        state: started
      ignore_errors: yes

    - name: use openpgp driver instead of PIV-II
      replace:
        path: /etc/opensc.conf
        replace: driver = "openpgp";
        regexp: driver = "PIV-II";

- name: enable pkgfile timer for missing binaries on Archlinux
  service:
    name: pkgfile-update.timer
    enabled: yes
  when: ansible_distribution == 'Archlinux'

- name: make sure configuring sudo doesn't cause everything to fail
  block:
    - name: configure sudo
      copy:
        src: sudo_config
        dest: /etc/sudoers.d/
        mode: 0440
        validate: /usr/sbin/visudo -cf %s
      become: yes

    - name: create admin user
      user:
        name: '{{ user_name }}'
        groups:
          - wheel
        update_password: on_create
        password: "{{ user_password|default('password')|password_hash('sha512', 65534|random(seed=user_password_salt)|string) }}"

    - name: lock root account
      user:
        name: root
        password_lock: yes

  rescue:
    - meta: noop
