---
- name: install user programs
  package:
    state: present
    name:
      - linux-zen
      - linux-zen-headers
      - bash-completion
      - moreutils
      - pkgfile
      - ccid
      - opensc
      - libusb-compat
      - thefuck
      - udiskie
      - lesspipe
      - sudo

- name: configure smartcard
  block:
    - name: enable smartcard service
      service:
        name: pcscd
        enabled: yes

    - name: start smartcard service
      service:
        name: pcscd
        state: started
      ignore_errors: yes

    - name: use openpgp driver instead of PIV-II
      replace:
        path: /etc/opensc.conf
        replace: driver = "openpgp";
        regexp: driver = "PIV-II";

- name: enable pkgfile timer for missing binaries on Archlinux
  service:
    name: pkgfile-update.timer
    enabled: yes
  when: ansible_distribution == 'Archlinux'

- name: configure sudo
  copy:
    src: sudo_config
    dest: /etc/sudoers.d/
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  become: yes

- name: create admin user
  user:
    name: '{{ user_name }}'
    groups: 
      - wheel
    update_password: on_create
    password: "{{ user_password|default(default_password)|password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
  register: admin
    
- name: lock root account
  user:
    name: root
    password_lock: yes
