---
- name: set the xyne repo architecture
  set_fact: xyne_architecture={{ ansible_architecture }}
  when: ansible_architecture in ['x86_64']

- name: configure support for xyne repo
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [xyne-{{ xyne_architecture|default("any") }}]
      SigLevel = Required
      Server = https://xyne.archlinux.ca/repos/xyne

- name: pull down new repos
  pacman:
    update_cache: yes

- name: install better package managers
  package:
    state: present
    name:
      - bauerbill
      - powerpill
      - pacserve
      - reflector
      - rsync
      - python3-threaded_servers

- name: enable pacserve
  service:
    name: pacserve
    enabled: yes

- name: start pacserve
  service:
    name: pacserve
    state: started
  ignore_errors: yes

- name: make powerpill make use of pacserve
  lineinfile:
    path: /etc/powerpill/powerpill.json
    regexp: '"server": '
    line: '"server": "http://localhost:15678"'
