---
- name: install graphical programs
  package: name={{ item }} state=present
  loop:
    - lightdm
    - lightdm-gtk-greeter
    - syncthing-gtk
    - qbittorent
    - kdeconnect
    - i3-gaps
    - i3blocks
    - i3lock
    - i3status
    - xorg
    - xterm
    - compton
    - xss-lock
    - feh
    - dunst
    - scrot
    - xdotool
    - dex
    - dmenu
    - terminux-font
    - arandr
    - redshift
    - python-xdg
    - xclip

    - chromium
    - ttf-liberation
    - noto-fonts
    - libu2f-host
    # - profile-sync-daemon
    # - chromium-widevine

- name: configure natural scrolling
  copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/
    
- name: start display manager
  service: name=lightdm enabled=yes state=started


      
