---
- name: install dotfiles
  copy:
    src: home/
    dest: "{{ admin.home }}/"
    owner: '{{ admin.name }}'
    group: '{{ admin.name }}'
    force: yes
    mode: preserve
  tags: dotfiles

- name: secure gpg directory
  file:
    path: "{{ admin.home}}/.gnupg"
    mode: og-rwx
    recurse: yes
  tags: gpg

- name: install bitwarden
  block:
    - name: firefox extension
      block:
        - command: mkdir -p /usr/lib/firefox-developer-edition/distribution/extensions/
        - get_url:
            url: https://addons.mozilla.org/firefox/downloads/file/1081305/bitwarden_free_password_manager-1.32.1-fx.xpi
            dest: /usr/lib/firefox-developer-edition/distribution/extensions/
      tags:
        - firefox
        - extension
  tags: bitwarden
