---
- name: lookup user info
  user:
    name: "{{ user_name }}"
  register: user
  tags:
    - always

- name: install dotfiles
  copy:
    src: home/
    dest: "{{ user.home }}/"
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    force: yes
    local_follow: no
  tags:
    - dotfiles

- name: secure gpg directory
  file:
    path: "{{ user.home }}/.gnupg"
    mode: og-rwx
    recurse: yes
  tags: gpg

- name: mark virtual machine directories as nocow
  file:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    path: "{{ user.home }}/{{ item }}"
    attributes: +C
    state: directory
  loop:
    - VirtualBox VMs
    - .local/share/libvirt/images

- name: install packages for the user
  ignore_errors: yes
  package:
    state: present
    name:
      - thefuck
      - udiskie
      - lesspipe
      - moreutils
      - unzip
      - unrar
      - wget
      - emacs
      - mu
      - offlineimap
      - lastpass-cli

      - npm

- name: perform installation and update tasks as user
  become: yes
  become_user: "{{ user.name }}"
  module_defaults:
    npm:
      state: latest
      global: yes
    command:
      chdir: "{{ user.home }}"
  block:
    - command: emacs --batch -l .emacs -f auto-package-update-now
    - npm:
        name: '@bitwarden/cli'
