---
- name: lookup user info
  user:
    name: "{{ user_name }}"
  register: user
  tags:
    - always

- name: install dotfiles
  copy:
    src: home/
    dest: "{{ user.home }}/"
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    force: yes
    local_follow: no
  tags:
    - dotfiles

- name: install binaries
  file:
    path: "{{ user.home }}/bin/"
    mode: +x
    recurse: yes
  tags:
    - dotfiles

- name: secure gpg directory
  file:
    path: "{{ user.home }}/.gnupg"
    mode: og-rwx
    recurse: yes
  tags:
    - dotfiles

- name: mark virtual machine directories as nocow
  ignore_errors: yes
  file:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    path: "{{ user.home }}/{{ item }}"
    attributes: +C
    state: directory
  loop:
    - VirtualBox VMs
    - .local/share/libvirt/images

- name: perform installation and update tasks as user
  become: yes
  become_user: "{{ user.name }}"
  ignore_errors: yes
  module_defaults:
    npm:
      state: latest
      global: yes
    command:
      chdir: "{{ user.home }}"
  block:
    - name: setup emacs
      command: emacs --batch -l .emacs.d/init.el -f install-and-update-packages
    - command: rustup default stable
    - name: setup stable rust
      command: rustup update
    - shell: feh --bg-fill "{{ background }}"
      args:
        creates: "{{ background }}"
      vars:
        background: "{{ user.home }}/Dropbox/linux_archlinux_os_blue_black_logo_30861_2560x1600.jpg"
      ignore_errors: yes
    - get_url:
        url: https://aka.ms/windev_VM_virtualbox
        dest: "{{ user.home }}/files/"
      tags:
        - downloads
        - never
