---
- name: lookup user info
  user:
    name: "{{ user_name }}"
  register: user

- name: install dotfiles
  block:
    - name: copy just portable files
      copy:
        src: home/{{ item }}
      loop:
        - .profile
        - .inputrc
        - .bashrc
        - .bash_profile
        - .screenrc
      tags:
        - basicdotfiles

    - name: copy full dotfiles
      copy:
        src: home/
      tags:
        - fulldotfiles

  module_defaults:
    copy:
      dest: "{{ user.home }}/"
      owner: '{{ user.name }}'
      group: '{{ user.group }}'
      force: yes
      local_follow: no
  tags:
    - dotfiles

- name: secure gpg directory
  file:
    path: "{{ user.home}}/.gnupg"
    mode: og-rwx
    recurse: yes
  tags: gpg
