---
- name: install developer tools
  package:
    state: present
    name:
      - base-devel
      - mlocate
      - openssh
      - x11-ssh-askpass
      - sshpass
      - pacman-contrib
      - ripgrep
      - sshfs
      - git
      - hub
      - python
      - python-pip
      - nodejs
      - npm
      - go
      - rustup
      - cmake
      - clang
      - gdb
      # - watchman

      - vagrant
      - virtualbox
      - docker
      - docker-compose
      - docker-machine

      - emacs
      - xclip
      - shellcheck
      - go-tools
      - flake8
      - autopep8
      - yapf
      - ipython
      - python-jedi
      - python-rope
      - python-virtualenv
      - prettier
      # - bear
      # - gocode-git

- name: enable updatedb to periodically run
  service:
    name: updatedb.timer
    enabled: yes

- name: start updatedb timer
  service:
    name: updatedb.timer
    state: started
  ignore_errors: yes
