---
- name: install ecryptfs packages
  package:
    state: present
    name: ecryptfs-utils

- name: configure automatic mounting of ecryptfs files
  block:
    - pamd:
        name: system-auth
        type: auth
        control: required
        module_path: pam_unix.so
        new_type: auth
        new_control: required
        new_module_path: pam_ecryptfs.so
        module_arguments: unwrap
        state: after

    - pamd:
        name: system-auth
        type: password
        control: required
        module_path: pam_unix.so
        new_type: password
        new_control: optional
        new_module_path: pam_ecryptfs.so
        state: before
        
    - pamd:
        name: system-auth
        type: session
        control: required
        module_path: pam_unix.so
        new_type: session
        new_control: optional
        new_module_path: pam_ecryptfs.so
        module_arguments: unwrap
        state: after
      
