---
- name: install better package managers
  package:
    state: present
    name:
      - bauerbill
      - powerpill
      - reflector
      - rsync
      - python3-threaded_servers

- name: make powerpill make use of pacserve
  lineinfile:
    path: /etc/powerpill/powerpill.json
    regexp: '"server": '
    line: '"server: "http://localhost:15678"'
