---
- name: install graphical programs
  package:
    state: present
    name:
      - lightdm
      - lightdm-gtk-greeter
      - accountsservice
      - syncthing-gtk
      - qbittorrent
      - kdeconnect
      - network-manager-applet
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
      - xorg
      - xterm
      - compton
      - xss-lock
      - feh
      - dunst
      - scrot
      - xdotool
      - dex
      - dmenu
      - terminus-font
      - arandr
      - redshift
      - python-xdg
      - xclip

      - chromium
      - ttf-liberation
      - noto-fonts
      - libu2f-host
      # - profile-sync-daemon
      # - chromium-widevine

      - firefox-developer-edition

- name: configure natural scrolling
  copy:
    src: '{{ item }}'
    dest: /etc/X11/xorg.conf.d/
  loop:
    - 30-keyboard.conf
    - 30-touchpad.conf

- name: allow redshift to access location
  blockinfile:
    path: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=
  tags: redshiftgeoclue

- name: create firefox global default extensions directory
  file:
    state: directory
    path: /usr/lib/firefox-developer-edition/distribution/extensions/

- name: install bitwarden to the global default extensions
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/1081305/bitwarden_free_password_manager-1.32.1-fx.xpi
    dest: /usr/lib/firefox-developer-edition/distribution/extensions/

- name: enable display manager
  service:
    name: lightdm
    enabled: yes

- name: start display manager
  service:
    name: lightdm
    state: started
  ignore_errors: yes
