---
- name: check for efi
  stat: path=/sys/firmware/efi/efivars
  register: sys_firmware_efi

- name: set the has_efi variable
  set_fact:
    has_efi: {{ sys_firware_efi.exists }}
    cacheable: yes

- name: install parted
  package: name=parted

- name: create data partition with room for esp
  parted:
    device: "{{ os_disk }}"
    number: 1
    state: present
    part_end: -1GiB
  when: has_efi or not encrypted_boot

- name: create data partition
  parted:
    device: "{{ os_disk }}"
    number: 1
    state: present
  when: not has_efi and encrypted_boot

- name: create esp
  parted:
    device: "{{ os_disk }}"
    state: present
    number: 2
    part_start: -1GiB
    flags: [ esp, boot ]

- name: add filesystem and more
  
