---
- name: check for efi
  stat: path=/sys/firmware/efi/efivars
  register: sys_firmware_efi

- name: set the has_efi variable
  set_fact:
    has_efi: '{{ sys_firware_efi.exists }}'
    cacheable: yes

- name: install parted
  package: name=parted

- name: create msdos disk label
  parted: device={{ os_disk }} label=msdos
  when: not has_efi

- name: create gpt disk label
  parted: device={{ os_disk }} label=gpt
  when: has_efi

- name: create boot partition
  parted: device={{ os_disk }} number=1 state=present part_end=1GiB

- name: set boot partition as esp
  parted: device={{ os_disk }} number=1 state=present flags=esp
  when: has_efi

- name: create data partition
  parted: device={{ os_disk }} number=2 state=present part_start=1GiB

- name: create keyfile for encryption
  shell: head -c 4096 /dev/random > /dev/shm/keyfile
  args: creates=/dev/shm/keyfile

- name: setup encrypted disk
  command: cryptsetup luksFormat {{ os_disk_second_partition }} /dev/shm/keyfile
  when: encrypted_data

# TODO
