---
- name: install pacserve
  package: name=pacserve state=present

- name: start pacserve
  service: name=pacserve enabled=yes

- name: configure pacman to use pacserve
  lineinfile:
    path: /etc/pacman.d/repo_extra
    line: Include = /etc/pacman.d/pacserve
