---
- name: rebuild initramfs
  command: mkinitcpio -P

- name: install bootloader to disk
  command: grub-install --recheck {{ boot_device }}

- name: update bootloader config
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: mirrorlist update
  pacman:
    update_cache: yes
    force: yes
