---
- name: rebuild initramfs
  command: mkinitcpio -P

- name: mirrorlist update
  pacman:
    update_cache: yes
    force: yes
  tags:
    - update

- name: grub config
  command: grub-mkconfig -o /boot/grub/grub.cfg
  listen: kernel update

- name: remount data dir
  command: mount -o remount /data
