---
- name: configure repo
  copy:
    dest: /etc/conf.d/ansible-pull
    content: REPO={{ current_repo }}

- name: install service files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: reload systemd
  systemd:
    daemon_reload: yes
  ignore_errors: yes

- name: enable the ansible-pull system
  service:
    name: ansible-pull.timer
    enabled: yes

- name: start ansible-pull timer
  service:
    name: ansible-pull.timer
    state: started
  ignore_errors: yes
