---
- name: install power saver
  package: name=tlp state=present

- name: start power saver
  service: name=tlp enabled=yes state=started

- name: enable tlp-sleep
  service: name=tlp-sleep enabled=yes
  
- name: disable systemd-rfkill service
  systemd: name=systemd-rfkill.service masked=yes

- name: disable systemd-rfkill socket
  systemd: name=systemd-rfkill.socket masked=yes

# - systemd: name=NetworkManager.service masked=yes
#   when: not use_network_manager

