---
- name: install printing packages
  pacman:
    name:
      - cups
      - ghostscript
      - foomatic-db
      - sane
- name: allow wheel group to control the printing service
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: ^SystemGroup
    line: SystemGroup sys root wheel
  become: yes
  notify:
    - reload print service
- name: start the printing service
  service: name=org.cups.cupsd enabled=yes state=started
