---
- name: install printing packages
  package:
    name:
      - cups
      - ghostscript
      - foomatic-db
      - sane
    state: present
      
- name: prevent become from killing everything
  block:
    - name: allow wheel group to control the printing service
      lineinfile:
        path: /etc/cups/cups-files.conf
        regexp: ^SystemGroup
        line: SystemGroup sys root wheel
      become: yes
      notify:
        - reload print service

  rescue:
    - meta: noop
    
- name: enable the printing service
  service:
    name: org.cups.cupsd
    enabled: yes

- name: start the printing service
  service:
    name: org.cups.cupsd
    state: started

