---
- name: set console keymap
  command: localectl set-keymap emacs

- name: setup system locale
  locale_gen: name={{ system_locale }}

- name: set locale
  command: localectl set-locale {{ system_locale }}

- name: set X11 keymap
  command: localectl set-x11-keymap us

- name: set console font
  lineinfile:
    path: /etc/vconsole.conf
    line: FONT=Lat2-Terminus16
    regexp: ^FONT

- name: set timezone
  command: timedatectl set-timezone {{ system_timezone }}

- name: install reflector for mirrorlist updates
  package: name=reflector state=present
      
- name: refresh mirrorlist
  command: reflector --save /etc/pacman.d/mirrorlist --sort rate --fastest 5 --country {{ country_code }}

- name: update system
  pacman:
    update_cache: yes
    upgrade: yes

- name: install intel microcode
  package: name=intel-ucode state=present
  when: "'GenuineIntel' in ansible_processor"
  notify:
    - update bootloader config

- name: automatically clean up the pacman cache
  copy: src=paccache.hook dest=/etc/pacman.d/hooks/

- name: relax umask
  lineinfile:
    path: /etc/profile
    line: umask 002
    regexp: ^umask

- name: automatically trim the system
  service: name=fstrim.timer enabled=yes state=started

- name: use systemd for initramfs
  lineinfile:
    path: /etc/mkinitcpio.conf
    line: HOOKS=(systemd autodetect sd-vconsole sd-encrypt sd-lvm2 modconf block keyboard filesystems)
    regexp: ^HOOKS
  notify:
    - rebuild initramfs

- name: install grub bootloader
  package: name=grub state=present
  notify:
    - update bootloader config
