---
- name: setup mirrorlist
  copy:
    dest: /etc/pacman.d/
    src: mirrorlist
  notify: mirrorlist update

- name: automatically clean up the pacman cache
  copy:
    src: paccache.hook
    dest: /etc/pacman.d/hooks/

- name: initialize pacman keyring
  command: pacman-key --init
  args:
    creates: /etc/pacman.d/gnupg/

- name: populate with standard package keys
  command: pacman-key --populate archlinux
  args:
    creates: /etc/pacman.d/gnupg/tofu.db

- name: install needed extras
  package:
    state: present
    name:
      - linux-headers

- name: install intel microcode
  package:
    name: intel-ucode
    state: present
  when: "'GenuineIntel' in ansible_processor"
  notify: kernel update

- name: set the xyne repo architecture
  set_fact: xyne_architecture={{ ansible_architecture }}
  when: ansible_architecture in ['x86_64']

- name: configure package repos
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

      [xyne-{{ xyne_architecture|default("any") }}]
      SigLevel = Required
      Server = http://xyne.archlinux.ca/bin/repo.php?file=

- name: pull down new repos
  pacman:
    update_cache: yes

- name: install better package managers
  package:
    state: present
    name:
      - bauerbill
      - powerpill
      - pacserve
      - reflector
      - rsync
      - python3-threaded_servers

- name: enable pacserve
  service:
    name: pacserve
    enabled: yes

- name: start pacserve
  service:
    name: pacserve
    state: started
  ignore_errors: "{{ not ansible_is_chroot }}"

- name: make powerpill make use of pacserve
  lineinfile:
    path: /etc/powerpill/powerpill.json
    regexp: '"server": '
    line: '"server": "http://localhost:15678"'
