- name: set local hostname
  copy:
    dest: /etc/hostname
    content: |
      {{ inventory_hostname }}

- name: set console keymap
  lineinfile:
    path: /etc/vconsole.conf
    line: KEYMAP={{ system_keymap }}
    regexp: ^KEYMAP
    create: yes

- name: setup system locale
  locale_gen:
    name: "{{ system_locale }}.{{ system_encoding }}"

- name: setup fallback locale
  locale_gen:
    name: en_US.UTF-8

- name: set locale
  lineinfile:
    path: /etc/locale.conf
    line: LANG={{ system_locale }}.{{ system_encoding }}
    regexp: ^LANG=
    create: yes

- name: set console font
  lineinfile:
    path: /etc/vconsole.conf
    line: FONT=Lat2-Terminus16
    regexp: ^FONT
    create: yes

- name: set timezone
  file:
    src: /usr/share/zoneinfo/{{ system_timezone }}
    dest: /etc/localtime
    state: link

- name: automatically trim the system
  service:
    name: fstrim.timer
    enabled: yes

- name: install grub for next step
  package:
    state: present
    name: grub

- name: reduce boot-up time on grub
  lineinfile:
    line: GRUB_TIMEOUT=2
    regexp: ^GRUB_TIMEOUT
    path: /etc/default/grub
  notify:
    - grub config

- name: setup data disk
  when: "'DATA' in ansible_device_links.labels.values()|flatten"
  block:
    - name: create mount point for data
      file:
        state: directory
        path: /data

    - name: mount the directory
      lineinfile:
        path: /etc/fstab
        line: LABEL=DATA /data auto nofail,noauto,x-systemd.automount 0 0
        regexp: DATA
      notify: remount data dir

- name: add user password to encrypted disk
  expect:
    command: cryptsetup -q luksAddKey --key-file /etc/keyfiles/{{ ansible_local.encrypted_disk }} /dev/disk/by-uuid/{{ ansible_local.encrypted_disk }}
    responses:
      passphrase: "{{ user_pass }}"
  when: ansible_local.encrypted_disk is defined
  ignore_errors: yes
