- name: setup data disk
  when: "'DATA' in ansible_device_links.labels.values()|flatten"
  block:
    - name: create mount point for data
      file:
        state: directory
        path: /data

    - name: mount the directory
      lineinfile:
        path: /etc/fstab
        line: LABEL=DATA /data auto nofail 0 0
