---
- name: check for efivars directory
  stat:
    path: /sys/firmware/efi/efivars/
  register: efivars

- debug:
    var: efivars

- name: record efi
  set_fact:
    has_efi: "{{ efivars.stat.exists }}"
    cacheable: yes
