---
- name: set local hostname
  copy:
    dest: /etc/hostname
    content: |
      {{ inventory_hostname }}

- name: set console keymap
  lineinfile:
    path: /etc/vconsole.conf
    line: KEYMAP={{ system_keymap }}
    regexp: ^KEYMAP

- name: setup system locale
  locale_gen:
    name: "{{ system_locale }}.{{ system_encoding }}"

- name: set locale
  lineinfile:
    path: /etc/locale.conf
    line: LANG={{ system_locale }}.{{ system_encoding }}
    regexp: ^LANG=

- name: set console font
  lineinfile:
    path: /etc/vconsole.conf
    line: FONT=Lat2-Terminus16
    regexp: ^FONT

- name: set timezone
  file:
    src: /usr/share/zoneinfo/{{ system_timezone }}
    dest: /etc/localtime
    state: link

- name: set the umask
  lineinfile:
    path: /etc/profile
    line: umask {{ system_umask }}
    regexp: ^umask

- name: automatically trim the system
  service:
    name: fstrim.timer
    enabled: yes

- name: add support for btrfs filesystems
  package:
    name: btrfs-progs
    state: present
  when: "'btrfs' in ansible_mounts|map(attribute='fstype')"

- name: enable autodefrag and user_subvol_rm_allowed on btrfs filesystems
  mount:
    fstype: '{{ item.fstype }}'
    opts: autodefrag,user_subvol_rm_allowed
    path: '{{ item.mount }}'
    src: UUID={{ item.uuid }}
    state: mounted
  when: item.fstype == 'btrfs'
  loop: '{{ ansible_mounts }}'

- import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'
    
