---
- import_tasks: discover-x86.yml
  when: ansible_architecture in ["i386", "x86_64"]
- import_tasks: basic.yml
- import_tasks: swap.yml
- import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'
- import_tasks: btrfs.yml
- import_tasks: update.yml
  tags:
    - update
    - never
- import_tasks: grub.yml
  when: ansible_architecture in ["i386", "x86_64"]
