---
- import_tasks: efi.yml
- import_tasks: basic.yml
- import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'
- import_tasks: btrfs.yml
- import_tasks: update.yml
  tags:
    - update
    - never
- import_tasks: grub.yml
