- when: encryption == 'none'
  block:
    - crypttab:
        name: /dev/mapper/swap
        opts: swap
        password: /dev/urandom
        state: present
        backing_device: /dev/rootvol/swap

    - mount:
        path: none
        fstype: swap
        state: present
        src: /dev/mapper/swap

- when: encryption == 'disk'
  block:
    - command: swapon /dev/rootvol/swap

  rescue:
    - command: mkswap -L SWAP /dev/rootvol/swap

    - command: swapon /dev/rootvol/swap

- when: encryption == 'disk'
  set_fact:
    resume_device: /dev/rootvol/swap
