---
- name: install grub bootloader
  package: name=grub state=present
  notify:
    - update bootloader config
    - install grub to firmware

- name: store kernel command line in grub config
  lineinfile:
    path: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="{{ cmdline }}"
    regexp: ^GRUB_CMDLINE_LINUX=
  notify:
    - update bootloader config

- name: set bootloader wait time
  lineinfile:
    path: /etc/default/grub
    line: GRUB_TIMEOUT={{ bootloader_wait_secs }}
    regexp: ^GRUB_TIMEOUT=
  notify:
    - update bootloader config
