---
package_list:
  - lightdm
  - lightdm-gtk-greeter
  - syncthing-gtk
  - qbittorent
  - kdeconnect
  - network-manager-applet
  - i3-gaps
  - i3blocks
  - i3lock
  - i3status
  - xorg
  - xterm
  - compton
  - xss-lock
  - feh
  - dunst
  - scrot
  - xdotool
  - dex
  - dmenu
  - terminus-font
  - arandr
  - redshift
  - python-xdg
  - xclip

  - chromium
  - ttf-liberation
  - noto-fonts
  - libu2f-host
  # - profile-sync-daemon
  # - chromium-widevine
