---
user_name: kieran
default_password: password
package_list:
  - base
  - base-devel
  - linux-zen
  - linux-zen-headers
  - base-devel
  - bash-completion
  - pacman-contrib
  - moreutils
  - mlocate
  - ripgrep
  - git
  - sshfs
  - openssh
  - pkgfile
  - ccid
  - hub
  - thefuck
  # - watchman
  - udiskie
  - python
  - python-pip
  - nodejs
  - npm
  - go
  - rust
  - cmake
  - clang

  - emacs
  - xclip
  - shellcheck
  - aspell
  - aspell-en
  - go-tools
  - flake8
  - autopep8
  - yapf
  - ipython
  - python-jedi
  - python-rope
  - python-virtualenv
  - prettier
  # - bear
  # - gocode-git

