user_name: "{{ lookup('lastpass', 'machine/' + inventory_hostname, field='username')|default('kieran') }}"
user_pass: "{{ lookup('lastpass', 'machine/' + inventory_hostname, field='password')|default('password') }}"
